# Generated by Django 3.2.20 on 2023-07-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval'), ('draft', 'Draft'), ('active', 'Active')], default='active', max_length=50),
        ),
    ]
