# Generated by Django 3.2.20 on 2023-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
