# Generated by Django 3.2.20 on 2023-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('draft', 'Draft'), ('active', 'Active'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
