# Generated by Django 3.2.20 on 2023-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
